name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools git unzip openjdk-17-jdk cython3
          pip3 install --user buildozer

      - name: Setup Android SDK/NDK
        run: |
          rm -rf ~/android-sdk ~/android-ndk*
          mkdir -p ~/android-sdk/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip
          mv cmdline-tools ~/android-sdk/cmdline-tools/latest
          
          cd ~/android-sdk
          ln -s cmdline-tools/latest tools
          
          yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=~/android-sdk --licenses
          ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=~/android-sdk "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip
          mv android-ndk-r25b ~/android-ndk

      - name: Build APK
        run: |
          export ANDROID_SDK_ROOT=~/android-sdk
          export ANDROID_NDK_HOME=~/android-ndk
          export PATH=$PATH:$HOME/.local/bin:~/android-sdk/cmdline-tools/latest/bin

          # Фиксируем настройки
          sed -i '/android.sdk/d; /android.ndk/d; /android.build_tools/d' buildozer.spec
          echo -e "\nandroid.ndk = 25b\nandroid.build_tools = 34.0.0" >> buildozer.spec
          
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: bin/*.apk
