name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            git \
            unzip \
            openjdk-17-jdk \
            zlib1g-dev \
            libncurses5-dev
          pip3 install --user buildozer

      - name: Install Android SDK/NDK
        run: |
          rm -rf ~/android-sdk ~/android-ndk*
          mkdir -p ~/android-sdk/cmdline-tools

          # Установите Command Line Tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip
          mv cmdline-tools ~/android-sdk/cmdline-tools/latest

          # Фикс для совместимости
          ln -sf ~/android-sdk/cmdline-tools/latest ~/android-sdk/tools

          # Примите все лицензии
          yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses --sdk_root=~/android-sdk

          # Установите компоненты (используйте 33.0.2 как стабильную)
          ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=~/android-sdk \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;33.0.2"

          # Установите NDK
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip
          mv android-ndk-r25b ~/android-ndk

          # Проверка Aidl
          ls -l ~/android-sdk/build-tools/33.0.2/aidl

      - name: Build APK
        run: |
          export ANDROID_SDK_ROOT=~/android-sdk
          export ANDROID_NDK_HOME=~/android-ndk
          export PATH=$PATH:$HOME/.local/bin:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin

          # Обновите buildozer.spec
          sed -i '/android.sdk/d; /android.ndk/d; /android.build_tools/d' buildozer.spec
          echo -e "\n[android]\nndk = 25b\nbuild_tools = 33.0.2" >> buildozer.spec

          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: bin/*.apk
