name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools git zip unzip openjdk-17-jdk cython3
          pip3 install --user buildozer

      - name: Set up Android SDK and NDK
        run: |
          # Установка Android Command Line Tools
          mkdir -p ~/android-sdk
          cd ~/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip
          mv cmdline-tools tools
          
          # Принятие лицензий
          yes | ./tools/bin/sdkmanager --licenses
          
          # Установка компонентов
          ./tools/bin/sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          
          # Установка NDK
          cd ~
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip android-ndk-r25b-linux.zip
          mv android-ndk-r25b android-ndk

      - name: Build APK
        run: |
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export ANDROID_NDK_HOME=$HOME/android-ndk
          export PATH=$PATH:$HOME/.local/bin
          
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: myapp.apk
          path: bin/*.apk
