name: Build APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools git zip unzip openjdk-17-jdk cython3
          pip3 install --user buildozer

      - name: Set up Android SDK and NDK
        run: |
          # Исправленный путь для Android SDK
          mkdir -p ~/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip
          mv cmdline-tools ~/android-sdk/cmdline-tools/latest
          
          # Принятие лицензий (обязательный шаг!)
          yes | ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=~/android-sdk --licenses
          
          # Установка компонентов
          ~/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=~/android-sdk "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          
          # Установка NDK
          wget https://dl.google.com/android/repository/android-ndk-r25c-linux.zip
          unzip android-ndk-r25c-linux.zip
          mv android-ndk-r25c ~/android-ndk

      - name: Build APK
        run: |
          export ANDROID_SDK_ROOT=~/android-sdk
          export ANDROID_NDK_HOME=~/android-ndk
          export PATH=$PATH:$HOME/.local/bin:~/android-sdk/platform-tools
          
          # Создание buildozer.spec при отсутствии
          buildozer init || true
          
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: myapp.apk
          path: bin/*.apk
